twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
      - 'bootstrap_4_layout.html.twig'
    globals:
      settings: '%settings%'
      app_github: '%app_github%'
      app_creator: '%app_creator%'